name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Git LFS and rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs rsync
          git lfs install

      - name: Prepare clean Hugging Face repo
        run: |
          mkdir /tmp/hfspace

          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            ./ /tmp/hfspace/

          cd /tmp/hfspace

          git init -b main
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"

          git lfs install --local
          git lfs track "*.xlsx"
          git lfs track "*.png"

          git add .gitattributes
          git add .
          git lfs ls-files || true

          git commit -m "Deploy to Hugging Face Space"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd /tmp/hfspace
          git push --force https://thebestian:$HF_TOKEN@huggingface.co/spaces/thebestian/fcn_datentool HEAD:main
